src/icfs/icfst.F90
=> Fix icfst.F90

meson.build, meson_options.txt, src/ampl/meson.build
@nimgould Do we also need `libcutest` if we want to compile the files in the `src/ampl` folder?
=> [Meson] AMPL interface

include/meson.build, src/ampl/meson.build, src/dum/meson.build
close #104 
Nick, can you review the PR?
=> [Meson] Update galahad_headers

.cirrus.yml, .github/workflows/standalone.yml
I reuse what I did for NOMAD: https://github.com/bbopt/nomad/blob/master/.cirrus.yml
=> Add CI for FreeBSD and ARM Macs

meson.build
=> [Meson] Use c_std=c99

.github/workflows/standalone.yml
=> Try the version 2023.2.0 of Intel compilers

GALAHAD.jl/test/test_bsc.jl, GALAHAD.jl/test/test_convert.jl, GALAHAD.jl/test/test_cro.jl, GALAHAD.jl/test/test_fit.jl, GALAHAD.jl/test/test_gls.jl, GALAHAD.jl/test/test_gltr.jl, GALAHAD.jl/test/test_hash.jl, GALAHAD.jl/test/test_ir.jl, GALAHAD.jl/test/test_l2rt.jl, GALAHAD.jl/test/test_lhs.jl, GALAHAD.jl/test/test_lms.jl, GALAHAD.jl/test/test_lpa.jl, GALAHAD.jl/test/test_lpb.jl, GALAHAD.jl/test/test_lsrt.jl, GALAHAD.jl/test/test_roots.jl, GALAHAD.jl/test/test_scu.jl, GALAHAD.jl/test/test_sec.jl, GALAHAD.jl/test/test_sha.jl, GALAHAD.jl/test/test_sils.jl, GALAHAD.jl/test/test_ugo.jl, GALAHAD.jl/test/test_wcp.jl, src/cro/C/crot.c, src/cro/C/crotf.c
=> Add examples for the Julia interface

GALAHAD.jl/test/test_cqp.jl, GALAHAD.jl/test/test_dps.jl, GALAHAD.jl/test/test_dqp.jl, GALAHAD.jl/test/test_eqp.jl, GALAHAD.jl/test/test_fdc.jl, GALAHAD.jl/test/test_glrt.jl, GALAHAD.jl/test/test_lsqp.jl, GALAHAD.jl/test/test_lstr.jl, GALAHAD.jl/test/test_psls.jl, GALAHAD.jl/test/test_sbls.jl
=> Julia examples

meson.build, meson_options.txt
=> Add an option libcutest_modules

.cirrus.yml, .github/workflows/standalone.yml, meson.build, src/ssids/gpu_factor.F90, src/ssids/ldlt_app.cxx
=> Upgrade SPRAL

include/spral_compat.hxx, include/spral_config.h, src/spral/compat.cxx
=> Update files related to SPRAL

.cirrus.yml, .github/workflows/standalone.yml, GALAHAD.jl/README.md, GALAHAD.jl/gen/README.md, GALAHAD.jl/gen/wrapper.jl, README.meson, meson.build, meson_options.txt
@nimgould 
Nick, I've finally taken the time to write documentation on Meson and the Julia interface GALAHAD.jl, as you requested.
=> More documentation about Meson and GALAHAD.jl

.cirrus.yml, .github/workflows/meson.yml
=> [CI] Test the Julia interface GALAHAD.jl

meson.build
All Fortran files are now preprocessed with the Meson build system.
=> [Meson] Preprocess *.f files

README.meson
=> Improve README.meson

GALAHAD.jl/LICENSE.md, LICENSE
Required for #264.
See https://github.com/JuliaRegistries/General/pull/101439
=> Add a license for GALAHAD.jl

.cirrus.yml
=> [CI] Fix Cirrus CI

GALAHAD.jl/src/wrappers/hsl.jl
It should fix the builds on Windows.
=> [GALAHAD.jl] Update hsl.jl with the new C headers

.github/workflows/meson.yml, meson.build
- Add a link flag related to OpenMP for C compilers.
- Remove old Intel compilers on Windows.
- Add tests with NVIDIA compilers.
=> Fix some compilation issues

.github/workflows/meson.yml, README.meson, meson.build, meson_options.txt
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
=> Update PATH on Windows

README.meson, meson.build, meson_options.txt, src/metis/meson.build
=> Compile the version of METIS provided by GALAHAD by default

.github/meson/action.yml, include/galahad_modules.h
=> Test GALAHAD with MKL

README.md
=> Add README section for precompiled GALAHAD

GALAHAD.jl/Project.toml, GALAHAD.jl/README.md, GALAHAD.jl/test/runtests.jl
close #343 
@nimgould The package `VERSION` seems to have a bug. When I call it from Julia, it hangs indefinitely.
All the other tests passed so I will still update the Julia interface.
We can investigate the issue later...
=> [GALAHAD.jl] Release 0.3.1

GALAHAD.jl/Project.toml
=> [GALAHAD.jl] Release 0.3.2

GALAHAD.jl/test/test_lhs.jl
=> Fix the Julia test of LHS

.github/meson/action.yml, .github/workflows/moonshot.yml
=> [CI] Use Moonshot at ANL

.github/meson/action.yml, .github/workflows/meson.yml
It's failing when I compile CUTEst not GALAHAD.
Relate PR: https://github.com/ralna/CUTEst/pull/76
=> [CI] Test the compilation of GALAHAD with nvfortran

meson.build, src/buildspec/meson.build, src/symbols/meson.build
=> Only compile one binary for buildspec and galahad_error

meson.build, src/version/version.F90
Require a fix for #421 before.
=> Release 5.2.1

.github/meson/action.yml
=> [CI] Fix Mac-Intel

GALAHAD.jl/test/test_arc.jl, GALAHAD.jl/test/test_blls.jl, GALAHAD.jl/test/test_bllsb.jl, GALAHAD.jl/test/test_bqpb.jl, GALAHAD.jl/test/test_ccqp.jl, GALAHAD.jl/test/test_clls.jl, GALAHAD.jl/test/test_cqp.jl, GALAHAD.jl/test/test_dgo.jl, GALAHAD.jl/test/test_dps.jl, GALAHAD.jl/test/test_dqp.jl, GALAHAD.jl/test/test_eqp.jl, GALAHAD.jl/test/test_fdc.jl, GALAHAD.jl/test/test_l2rt.jl, GALAHAD.jl/test/test_llsr.jl, GALAHAD.jl/test/test_llst.jl, GALAHAD.jl/test/test_lpb.jl, GALAHAD.jl/test/test_lsqp.jl, GALAHAD.jl/test/test_nls.jl, GALAHAD.jl/test/test_psls.jl, GALAHAD.jl/test/test_qpa.jl, GALAHAD.jl/test/test_qpb.jl, GALAHAD.jl/test/test_rqs.jl, GALAHAD.jl/test/test_sbls.jl, GALAHAD.jl/test/test_slls.jl, GALAHAD.jl/test/test_trb.jl, GALAHAD.jl/test/test_trs.jl, GALAHAD.jl/test/test_tru.jl, GALAHAD.jl/test/test_wcp.jl
Similar to what did @nimgould with the Fortran tests.
=> [GALAHAD.jl] Use the linear solvers of LAPACK for unit tests

.github/meson/action.yml, src/external/hsl/hsl_kb22/hsl_kb22l.f90, src/external/hsl/hsl_ma48/hsl_ma48r.f90, src/external/hsl/hsl_ma54/hsl_ma54r.f90, src/external/hsl/hsl_ma57/hsl_ma57r.f90, src/external/hsl/hsl_ma64/hsl_ma64r.f90, src/external/hsl/hsl_ma77/hsl_ma77r.f90, src/external/hsl/hsl_ma86/hsl_ma86r.f90, src/external/hsl/hsl_ma87/hsl_ma87r.f90, src/external/hsl/hsl_ma97/hsl_ma97r.f90, src/external/hsl/hsl_mc34/hsl_mc34r.f90, src/external/hsl/hsl_mc64/hsl_mc64r.f90, src/external/hsl/hsl_mc69/hsl_mc69r.f90, src/external/hsl/hsl_mc80/hsl_mc80r.f90, src/external/hsl/hsl_mi20/hsl_mi20r.f90, src/external/hsl/hsl_mi28/hsl_mi28r.f90, src/external/hsl/hsl_mi35/hsl_mi35r.f90, src/external/hsl/hsl_of01/hsl_of01r.f90, src/external/hsl/hsl_zb01/hsl_zb01r.f90, src/sls/sls.F90
=> Allow hot-swapping of the HSL library

.github/coverage/exclude_files.txt, GALAHAD.jl/src/GALAHAD.jl, GALAHAD.jl/src/wrappers/version.jl, GALAHAD.jl/test/runtests.jl, GALAHAD.jl/test/test_ccqp.jl, GALAHAD.jl/test/test_version.jl, src/forthcoming/expo/Python/expo_pyiface.c, src/forthcoming/expo/Python/test_expo.py, src/forthcoming/expo/meson.build, src/tru/Python/tru_pyiface.c
@nimgould 
After this PR, all components of SSLS and EXPO are compiled and tested.
I know they are failing, I tested them locally (compilation or execution) during my flight.
You can merge the PR if you want, but it will only introduce new failures.
I suggest fixing the builds on master before adding more things to fix.
My shift ends for tonight, I'll let you take over. Our collaboration really follows a 3-shift rotation schedule! ;)
=> More fixes for SSLS and EXPO

.github/meson/action.yml, include/galahad_expo.h, src/forthcoming/expo/Python/expo_pyiface.c, src/forthcoming/expo/meson.build, src/version/C/versiont.c
=> Fix compilation warning for EXPO and VERSION

src/forthcoming/expo/meson.build
close #452 
Comment for Nick: Only merge the PR if all tests passed!
Jari / Nick, you can use this branch to debug / fix `test_expo.py`.
=> Debug test_expo.py

.github/workflows/build_wheels.yml
=> [CI] Build python wheels on version tags

.github/workflows/galahad_c.yml, GALAHAD.jl/gen/galahad_c.jl, GALAHAD.jl/gen/rewriter.jl, GALAHAD.jl/gen/wrapper.jl, include/galahad_c_double.h, include/galahad_c_quadruple.h, include/galahad_c_single.h, include/galahad_callbacks.h
Related issue #464 
Still need to use templated function callbacks introducted in #477.
=> Generate galahad_c.h with Julia

GALAHAD.jl/gen/examples.jl, GALAHAD.jl/gen/galahad_c.jl, GALAHAD.jl/gen/rewriter.jl, GALAHAD.jl/gen/wrapper.jl, include/galahad_c_common.h, src/version/Julia/test_version.jl
=> Add the package VERSION in galahad_c.h

include/galahad.h, include/meson.build
=> [Meson] Install the multiprecision headers for the next release

GALAHAD.jl/Project.toml
cc @dpo 
All tests passed with the new JLL: https://github.com/ralna/GALAHAD/actions/runs/17497209110/job/49701035318?pr=508
=> [GALAHAD.jl] Release 0.5.0
