- src/slls/slls.F90
It solved the following error:
```shell
FAILED: libgalahad_single.so.p/src_slls_slls.F90.o libgalahad_single.so.p/galahad_slls_precision.mod 
gfortran -Ilibgalahad_single.so.p -I. -I.. -I../include -Ilibgalahad_metis.so.p -Ilibpastix_single.so.p -Ilibwsmp.so.p -Ilibspmf.so.p -Ilibmumps_single.so.p -Ilibspral_ssids_single.so.p -Ilibmkl_pardiso.so.p -Ilibpardiso.so.p -Ilibgalahad_hsl_double.so.p -Ilibgalahad_hsl_single.so.p -Ilibgalahad_lapack.so.p -Ilibgalahad_blas.so.p -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -DGALAHAD_SINGLE -Jlibgalahad_single.so.p -o libgalahad_single.so.p/src_slls_slls.F90.o -c ../src/slls/slls.F90
../src/slls/slls.F90:70:22:
70 |      USE GALAHAD_KINDS
|                      1
Error: Unexpected USE statement in INTERFACE block at (1) …
```
> Fix an error during the compilation of slls

- include/hsl_mc68.h
- meson.build
- meson_options.txt
I tested the compilation of GALAHAD with JuliaHSL tonight and it worked. :100: 
```shell
meson setup builddir_julia --prefix=~/Applications/galahad \
-Dmodules=true \
-Dlibhsl_path=/home/alexis/Applications/juliahsl/lib \
-Dlibhsl_modules=/home/alexis/Applications/juliahsl/modules \
-Dlibmetis_path=/home/alexis/Applications/metis-5.1.0/install/lib
```
ps: I also updated the header file of `hsl_mc68`.
> [Meson] Link GALAHAD with JuliaHSL

- doc/paper_v4/paper.md
@jfowkes @nimgould 
I was reading your JOSS paper yesterday and I found two typos.
For the table, your could maybe use `\hspace{-6cm}` such that the second column has more width.
> Fix two typos in paper.md

- meson.build
- meson_options.txt
- src/dum/meson.build
- src/dum/metis4.f
- src/external/meson.build
- src/external/metis/dummy_metis.f90
- src/external/metis/meson.build
- src/external/metis/metis4.f90
- src/external/metis/metis5.f90
- src/external/metis/metis5_adapter.c
In brief, I use fortran preprocessing to replace `metis_nodend` by `galahad_metis`.
We have three versions of `galahad_metis` (dummy, metis4, metis5).
They are based on the API of METIS 4 so we don't need to update the source code of GALAHAD.
I removed `src/dum/metis4.f` because it's replaced by `src/external/metis/dummy_metis.f90`.
> Support METIS 5 in GALAHAD

- meson_options.txt
@nimgould 
We can use the library `libmkl_rt.so` to link with all functions of oneMKL.
> The default shared library for libmkl_pardiso is mkl_rt

- .cirrus.yml
- .github/workflows/standalone.yml
It seems that some platforms find `libblas.${dlext}` and  `liblapack.${dlext}`.
It could explain why we have tests that fail only on some platforms.
> Use BLAS and LAPACK routines provided by GALAHAD for CI builds

- meson.build
- meson_options.txt
- src/external/metis/meson.build
Nick added the header `metis.h` of METIS 5 in `include`, we don't need anymore to provide a path to find it.
> Remove the option to provide the header of METIS5

- meson.build
- src/lapack/meson.build
@nimgould 
I updated the main `meson.build` such that the preprocessed files have the extension `.f90` and I don't use anymore the `-cpp` / `-fpp` flag when I compile them.
It fixed the errors with `nagfor` and removed the warnings "bad # preprocessor line" with `ifort`.
However, I have this new error with the NAG compiler:
```shell
FAILED: libgalahad_single.so.p/meson-generated_single_contrib.f90.o 
libgalahad_single.so.p/spral_ssids_contrib_single.mod 
nagfor -Ilibgalahad_single.so.p -I. -I.. -Iinclude -I../include -I../src/dum/include -Isrc/ampl -I../src/ampl -quiet -w=all -O0 -g -dcfuns -Dmetis_nodend=galahad_metis -PIC -DSPRAL_NO_SCHED_GETCPU -DSPRAL_HAVE_HWLOC -DGALAHAD_SINGLE -DSPRAL_SINGLE -mdir libgalahad_single.so.p -o libgalahad_single.so.p/meson-generated_single_contrib.f90.o …
```
> Update how we preprocess Fortran files

- .cirrus.yml
- .github/workflows/standalone.yml
- meson_options.txt
@nimgould 
I updated the default value for BLAS and LAPACK libraries.
It's `libopenblas.${dlext}` by default now.
If it's not found, we compile our own version.
I don't want that we link with the `libblas.dylib` and `liblapack.dylib` provided by Apple.
> Use OpenBLAS as the default library for BLAS and LAPACK routines

- include/ssids_cpu_NumericSubtree.hxx
- src/ssids/ldlt_app.cxx
@jfowkes @nimgould 
By commenting the lines with `#pragma omp cancellation point taskgroup` in SSIDS, I fixed the compilation with Intel compilers.
> Comment #pragma omp cancellation point taskgroup in C++ code of SSIDS

- meson.build
An old modification that I forgot to push. Nick it could be relevant for your build system based on makemaster files.
It's `/Qopenmp` for Intel compilers on Windows.
> Update the flag for OpenMP on Windows

- .github/workflows/standalone.yml
- meson.build
- meson_options.txt
@nimgould  @jfowkes 
I added an option `galahad_int64` in the Meson build system to compile with the flag  `-DGALAHAD_64BIT_INTEGER`.
Should I use a different name of does it make sense to you?
I also added a CI build that compiles BLAS and LAPACK with 64 bits integer such that we can test this option with continuous integration.
Note that we have many errors with this option (see [here](https://github.com/ralna/GALAHAD/suites/18429890758/artifacts/1068313560)).
> Test the option -DGALAHAD_64BIT_INTEGER

- README.meson
- meson.build
- meson_options.txt
- src/dum/meson.build
@nimgould 
I removed the option to specify a library for MKL Pardiso because the library `mkl_rt` already includes the BLAS and LAPACK symbols.
Using two libraries, such as libopenblas.so and libmkl_rt.so, may lead to potential issues.
To determine if Intel MKL Pardiso is available, I now simply check the values of `libblas` and `liblapack`.
> [Meson] Remove the option to provide libmkl_pardiso

- src/lapack/meson.build
close #233
@nimgould 
`libgalahad_f_src` is for `*.f` files.
`libgalahad_src` is for `*.f90` or `*.F90` files.
I explained it [here](https://github.com/ralna/GALAHAD/blob/master/meson.build#L168-L214).
Should I also add it in the `README.meson`?
> Fix lapack/meson.build

- .github/julia/check_macros.jl
- src/lapack/README.rebuild
- Add an option to exclude some Fortran files
- Don't check the length of lines that are comments
> Improve check_macros.jl

- include/metis.h
- meson.build
- Support 64-bit integer version of METIS;
- Fix a bug with `croti.F90`;
- Don't compile the examples with the 64-bit integer version of GALAHAD.
> Fix more issue for 64-bit integer

- .github/workflows/meson.yml
- src/trb/C/trbs2.c
Errors that I found in the logs:
```shell
At line 416 of file ../src/hash/hash.F90
Fortran runtime error: Unit number in I/O statement too large
```
```shell
----------------------------------- stderr -----------------------------------
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
libc.so.6          00007FDF78E42520  Unknown               Unknown  Unknown
libgalahad_double  00007FDF7A7ECB3F  spral_ssids_anal_         592  anal.F90
libgalahad_double  00007FDF7A7EA6DA  spral_ssids_anal_         397  anal.F90
libgalahad_double  00007FDF7A7F3695  spral_ssids_anal_        1041  anal.F90
libgalahad_double  00007FDF7A7FE307  spral_ssids_doubl         384  ssids.F90
libgalahad_double  00007FDF7A6E5B23 …
```
> [CI] Add more builds

- .github/workflows/meson.yml
- include/galahad_dgo.h
```
C sparse matrix indexing
tests options for all-in-one storage format
DGO solver, problem:  (n = 3)
At line 416 of file ../src/hash/hash.F90
Fortran runtime error: Unit number in I/O statement too large
```
> Try to debug DGO issue with Int64

- .cirrus.yml
- .github/workflows/meson.yml
- meson.build
We should `dlopen` the shared library like Ipopt to avoid the issue with missing symbols.
> [CI] Compile GALAHAD with CUTEst

- .github/julia/check_headers.jl
- .github/workflows/headers.yml
- GALAHAD.jl/src/wrappers/arc.jl
- GALAHAD.jl/src/wrappers/bnls.jl
- GALAHAD.jl/src/wrappers/rpd.jl
- GALAHAD.jl/src/wrappers/sha.jl
- GALAHAD.jl/src/wrappers/ssids.jl
- GALAHAD.jl/src/wrappers/trb.jl
- include/galahad_arc.h
- include/galahad_bgo.h
- include/galahad_bnls.h
- include/galahad_rpd.h
- include/galahad_sha.h
- include/galahad_trb.h
- include/galahad_tru.h
- include/galahad_ugo.h
- include/spral_ssids.h
- src/dum/C/ssids_ciface.F90
- src/sils/C/sils_ciface.F90
@nimgould @jfowkes 
This PR adds a new CI workflow `headers.yml` that will test at each commit that the C headers are consistent with the structures defined in the Fortran files (`*_ciface.F90`).
Just like the workflows related to macros, symbols and modules, it should help us to develop new packages. 
Jari, I suppose that we should also improve this test to check that the initial structures in Fortran like in `arc.F90` are consistent with the Fortran file `arc_ciface.F90`?
I found the following errors:
```julia
-------------------------------------------------------------
The following structures are only defined in the header files
-------------------------------------------------------------
sils_ainfo_type
icfs_inform_type
icfs_control_type
sils_finfo_type
spral_ssids_inform …
```
> [CI] Add a new workflow check_headers.jl

- GALAHAD.jl/gen/rewriter.jl
- GALAHAD.jl/src/wrappers/uls.jl
- include/galahad_gls.h
- include/galahad_uls.h
- src/gls/C/gls_ciface.F90
- src/gls/Python/gls_pyiface.c
- src/uls/C/uls_ciface.F90
- src/uls/Python/uls_pyiface.c
@nimgould Is it fine for you?
It doesn't concern the code in Fortran, it's just the structures in the C interface that are renamed.
I always need some sed commands in the Julia interface because of this missing suffix.
Only `GLS` is concerned by this "issue".
> Add the suffix _type for the C structures in GLS

- .github/meson/action.yml
- .github/workflows/symbols.yml
- README.meson
- meson.build
- meson_options.txt
@jfowkes @nimgould 
I added an option to the Meson build so that the binaries are no longer compiled by default.
I believe the majority of users are not interested in these files, and making their compilation optional seems appropriate from my point of view.
I will wait a green light of you to merge the PR.
> [Meson] Add an option to compile or not the binaries

- src/cutest_functions/cutest_trampoline.F90
- src/cutest_functions/meson.build
As discussed this morning with @nimgould 
Users can now use the exported symbols `galahad_load_routines_r` and`galahad_unload_routines_r` to load / unload the shared libraries of the decoded SIF problems.
Relevant for all files `run*.F90`.
```shell
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ nm -D libgalahad_double.so | grep load_routines
U cutest_load_routines_
U cutest_unload_routines_
00000000028118d1 T galahad_load_routines_
00000000028118f5 T galahad_unload_routines_
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ nm -D libgalahad_single.so | grep load_routines
U cutest_load_routines_s_
U cutest_unload_routines_s_
0000000002806491 T galahad_load_routines_s_
00000000028064b5 T galahad_unload_routines_s_
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ nm -D …
```
> Add galahad_load_routines and galahad_unload_routines

- .github/workflows/build_wheels.yml
- meson.build
- pyproject.toml
- src/__init__.py
Finally with some nasty DLL hacking on Windows we can automatically precompile Python binaries on Windows.
> Automatically build Python wheels on Windows

- GALAHAD.jl/gen/wrapper.jl
- GALAHAD.jl/src/wrappers/bqp.jl
- GALAHAD.jl/src/wrappers/bqpb.jl
- GALAHAD.jl/src/wrappers/ccqp.jl
- GALAHAD.jl/src/wrappers/cdqp.jl
- GALAHAD.jl/src/wrappers/cqp.jl
- GALAHAD.jl/src/wrappers/dlp.jl
- GALAHAD.jl/src/wrappers/dqp.jl
- GALAHAD.jl/src/wrappers/lpa.jl
- GALAHAD.jl/src/wrappers/lpb.jl
- GALAHAD.jl/src/wrappers/qp.jl
- GALAHAD.jl/src/wrappers/qpa.jl
- GALAHAD.jl/src/wrappers/qpb.jl
- GALAHAD.jl/src/wrappers/qpc.jl
@nimgould How does QPLIB support work in single and quadruple precision? 
Does GALAHAD read the data in double precision and then perform the conversion?
Can you also confirm that the correct way to call a binary for QPLIB is:
```shell
runbpq_qplib_double < myfile.qplib
````
> Support the binaries for QPLIB in GALAHAD.jl

- GALAHAD.jl/gen/rewriter.jl
- GALAHAD.jl/src/wrappers/nls.jl
- include/galahad_arc.h
- include/galahad_bgo.h
- include/galahad_blls.h
- include/galahad_callbacks.h
- include/galahad_dgo.h
- include/galahad_expo.h
- include/galahad_nls.h
- include/galahad_slls.h
- include/galahad_trb.h
- include/galahad_tru.h
- include/galahad_ugo.h
- include/meson.build
@nimgould I worked on a  `galahad_callbacks.h` to easily reuse the signatures of GALAHAD callbacks in the various packages (and ensure a uniform API).
I also find that it is easier to understand the signature of the callbacks in the headers that support direct communication.
The users don't need to write the prototypes in their code too, they can do something like this:
```shell
galahad_f fun;
galahad_g grad;
galahad_h hess;
```
instead of 
```shell
// Function prototypes
ipc_ fun(ipc_ n, const rpc_ x[], rpc_ *f, const void *);
ipc_ grad(ipc_ n, const rpc_ x[], rpc_ g[], const void *);
ipc_ hess(ipc_ n, ipc_ ne, const rpc_ x[], rpc_ hval[], const void *);
```
Which allow to ensure that their callbacks respect what the C interface of GALAHAD routines require.
Otherwise they will have a …
> Add a header galahad_callbacks.h
